export default {
  1: "de Adão",
  2: "de Osasco",
  3: "de Mauá",
  4: "Demais",
  5: "de Araçatuba",
  6: "de Pindamonhangaba",
  7: "Alface",
  8: "Cavalo",
  9: "Quântico",
  10: "de Madureira",
  11: "Cabuloso/a",
  12: "Louco/a",
  13: "Xiaomi",
  14: "Apple",
  15: "Pineapple",
  16: "Ninja",
  17: "Stark",
  18: "Égua",
}
