export default {
  1: "Adão",
  2: "Osasco",
  3: "Mauá",
  4: "Demais",
  5: "Araçatuba",
  6: "Pindamonhangaba",
  7: "Alface",
  8: "Cavalo",
  9: "Quântico",
  10: "Madureira",
  11: "Cabuloso/a",
  12: "Louco/a",
  13: "Xiaomi",
  14: "Apple",
  15: "Pineapple",
  16: "Ninja",
  17: "Stark",
}
