export default {
  1: "Chapada de ",
  2: "Bochecha ",
  3: "Bob Esponja de ",
  4: "Capitã Marvel de ",
  5: "Darth ",
  6: "Baianinho de ",
  7: "U1000d ",
  8: "Gargamel de ",
  9: "Cabeça de ",
  10: "Smurf ",
  11: "Oscar de ",
  12: "Unicórnio ",
  13: "Cara de ",
  14: "Boca de ",
  15: "Mão de ",
  16: "Sacaninha de ",
  17: "Gandalf de ",
  18: "Coach ",
  19: "Thanos de ",
  20: "Rei da/o ",
  21: "Rainha da/o ",
  22: "Pikachu de ",
  23: "Ornitorrinco de ",
  24: "Baby Yoda de ",
  25: "Zelda ",
  26: "Sonic de ",
  27: "Mindinho de ",
  28: "Castor de ",
}
